# Prism Acid Rain - Alacritty
[colors.primary]
background = "#0d1117"
foreground = "#bc8cff"

[colors.normal]
black = "#0d1117"
red = "#7ee787"
green = "#f0883e"
yellow = "#58a6ff"
blue = "#7ee787"
magenta = "#58a6ff"
cyan = "#f0883e"
white = "#bc8cff"

[colors.bright]
black = "#0d1117"
red = "#7ee787"
green = "#f0883e"
yellow = "#58a6ff"
blue = "#7ee787"
magenta = "#58a6ff"
cyan = "#f0883e"
white = "#bc8cff"
