# Prism Biopic - Alacritty
[colors.primary]
background = "#faf8f5"
foreground = "#33302a"

[colors.normal]
black = "#33302a"
red = "#0859ba"
green = "#1a79ea"
yellow = "#8a8378"
blue = "#0969da"
magenta = "#0751a3"
cyan = "#2989fa"
white = "#faf8f5"

[colors.bright]
black = "#33302a"
red = "#0859ba"
green = "#1a79ea"
yellow = "#8a8378"
blue = "#0969da"
magenta = "#0751a3"
cyan = "#2989fa"
white = "#faf8f5"
