# Prism Blood Moon - Alacritty
[colors.primary]
background = "#090909"
foreground = "#f5f5f5"

[colors.normal]
black = "#090909"
red = "#d71b1f"
green = "#c2b9b7"
yellow = "#b0a8a6"
blue = "#968f8d"
magenta = "#6e0a09"
cyan = "#c9c1c0"
white = "#f5f5f5"

[colors.bright]
black = "#090909"
red = "#d71b1f"
green = "#c2b9b7"
yellow = "#b0a8a6"
blue = "#968f8d"
magenta = "#6e0a09"
cyan = "#c9c1c0"
white = "#f5f5f5"
