# Prism Coastal - Alacritty
[colors.primary]
background = "#001219"
foreground = "#E9D8A6"

[colors.normal]
black = "#001219"
red = "#005F73"
green = "#94D2BD"
yellow = "#0A9396"
blue = "#005F73"
magenta = "#0A9396"
cyan = "#94D2BD"
white = "#E9D8A6"

[colors.bright]
black = "#001219"
red = "#005F73"
green = "#94D2BD"
yellow = "#0A9396"
blue = "#005F73"
magenta = "#0A9396"
cyan = "#94D2BD"
white = "#E9D8A6"
