# Prism Faded Glory - Alacritty
[colors.primary]
background = "#FDF0D5"
foreground = "#003049"

[colors.normal]
black = "#003049"
red = "#780000"
green = "#669BBC"
yellow = "#C1121F"
blue = "#780000"
magenta = "#C1121F"
cyan = "#669BBC"
white = "#FDF0D5"

[colors.bright]
black = "#003049"
red = "#780000"
green = "#669BBC"
yellow = "#C1121F"
blue = "#780000"
magenta = "#C1121F"
cyan = "#669BBC"
white = "#FDF0D5"
