# Prism Forest - Alacritty
[colors.primary]
background = "#0D1F0A"
foreground = "#ACD322"

[colors.normal]
black = "#0D1F0A"
red = "#1E483C"
green = "#8AD0A2"
yellow = "#62A527"
blue = "#1E483C"
magenta = "#62A527"
cyan = "#8AD0A2"
white = "#ACD322"

[colors.bright]
black = "#0D1F0A"
red = "#1E483C"
green = "#8AD0A2"
yellow = "#62A527"
blue = "#1E483C"
magenta = "#62A527"
cyan = "#8AD0A2"
white = "#ACD322"
