# Prism Ghost - Alacritty
[colors.primary]
background = "#e8ecf0"
foreground = "#384452"

[colors.normal]
black = "#384452"
red = "#366da6"
green = "#5090d4"
yellow = "#7a8a9c"
blue = "#4080c4"
magenta = "#306093"
cyan = "#60a0e4"
white = "#e8ecf0"

[colors.bright]
black = "#384452"
red = "#366da6"
green = "#5090d4"
yellow = "#7a8a9c"
blue = "#4080c4"
magenta = "#306093"
cyan = "#60a0e4"
white = "#e8ecf0"
