# Prism Github - Alacritty
[colors.primary]
background = "#22272e"
foreground = "#d8e0e7"

[colors.normal]
black = "#22272e"
red = "#4793d8"
green = "#65b6ff"
yellow = "#545d68"
blue = "#54aeff"
magenta = "#3f82bf"
cyan = "#76beff"
white = "#d8e0e7"

[colors.bright]
black = "#22272e"
red = "#4793d8"
green = "#65b6ff"
yellow = "#545d68"
blue = "#54aeff"
magenta = "#3f82bf"
cyan = "#76beff"
white = "#d8e0e7"
