# Prism Gruvbox Material - Alacritty
[colors.primary]
background = "#282828"
foreground = "#d3869b"

[colors.normal]
black = "#282828"
red = "#fabd2f"
green = "#83a598"
yellow = "#b8bb26"
blue = "#fabd2f"
magenta = "#b8bb26"
cyan = "#83a598"
white = "#d3869b"

[colors.bright]
black = "#282828"
red = "#fabd2f"
green = "#83a598"
yellow = "#b8bb26"
blue = "#fabd2f"
magenta = "#b8bb26"
cyan = "#83a598"
white = "#d3869b"
