# Prism Holographic - Alacritty
[colors.primary]
background = "#0a0a0f"
foreground = "#b967ff"

[colors.normal]
black = "#0a0a0f"
red = "#ff71ce"
green = "#05ffa1"
yellow = "#01cdfe"
blue = "#ff71ce"
magenta = "#01cdfe"
cyan = "#05ffa1"
white = "#b967ff"

[colors.bright]
black = "#0a0a0f"
red = "#ff71ce"
green = "#05ffa1"
yellow = "#01cdfe"
blue = "#ff71ce"
magenta = "#01cdfe"
cyan = "#05ffa1"
white = "#b967ff"
