# Prism Memphis - Alacritty
[colors.primary]
background = "#000000"
foreground = "#d8e0e7"

[colors.normal]
black = "#000000"
red = "#4793d8"
green = "#65b6ff"
yellow = "#3a424f"
blue = "#54aeff"
magenta = "#3f82bf"
cyan = "#76beff"
white = "#d8e0e7"

[colors.bright]
black = "#000000"
red = "#4793d8"
green = "#65b6ff"
yellow = "#3a424f"
blue = "#54aeff"
magenta = "#3f82bf"
cyan = "#76beff"
white = "#d8e0e7"
