# Prism Minimal - Alacritty
[colors.primary]
background = "#f5f5f5"
foreground = "#161616"

[colors.normal]
black = "#161616"
red = "#e43938"
green = "#9e9894"
yellow = "#b0a8a6"
blue = "#8c8680"
magenta = "#7a1110"
cyan = "#c0b8b6"
white = "#f5f5f5"

[colors.bright]
black = "#161616"
red = "#e43938"
green = "#9e9894"
yellow = "#b0a8a6"
blue = "#8c8680"
magenta = "#7a1110"
cyan = "#c0b8b6"
white = "#f5f5f5"
