# Prism Mint - Alacritty
[colors.primary]
background = "#EDFDEE"
foreground = "#1B445F"

[colors.normal]
black = "#1B445F"
red = "#49BFC1"
green = "#A6F2B8"
yellow = "#74D2A9"
blue = "#49BFC1"
magenta = "#74D2A9"
cyan = "#A6F2B8"
white = "#EDFDEE"

[colors.bright]
black = "#1B445F"
red = "#49BFC1"
green = "#A6F2B8"
yellow = "#74D2A9"
blue = "#49BFC1"
magenta = "#74D2A9"
cyan = "#A6F2B8"
white = "#EDFDEE"
