# Prism Neoform - Alacritty
[colors.primary]
background = "#e8ecf2"
foreground = "#2d3848"

[colors.normal]
black = "#2d3848"
red = "#0859ba"
green = "#1a79ea"
yellow = "#8896a8"
blue = "#0969da"
magenta = "#0751a3"
cyan = "#2989fa"
white = "#e8ecf2"

[colors.bright]
black = "#2d3848"
red = "#0859ba"
green = "#1a79ea"
yellow = "#8896a8"
blue = "#0969da"
magenta = "#0751a3"
cyan = "#2989fa"
white = "#e8ecf2"
