# Prism Night Owl - Alacritty
[colors.primary]
background = "#011627"
foreground = "#f78c6c"

[colors.normal]
black = "#011627"
red = "#82aaff"
green = "#7fdbca"
yellow = "#c792ea"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#7fdbca"
white = "#f78c6c"

[colors.bright]
black = "#011627"
red = "#82aaff"
green = "#7fdbca"
yellow = "#c792ea"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#7fdbca"
white = "#f78c6c"
