# Prism Nord Aurora - Alacritty
[colors.primary]
background = "#2e3440"
foreground = "#bf616a"

[colors.normal]
black = "#2e3440"
red = "#88c0d0"
green = "#a3be8c"
yellow = "#81a1c1"
blue = "#88c0d0"
magenta = "#81a1c1"
cyan = "#a3be8c"
white = "#bf616a"

[colors.bright]
black = "#2e3440"
red = "#88c0d0"
green = "#a3be8c"
yellow = "#81a1c1"
blue = "#88c0d0"
magenta = "#81a1c1"
cyan = "#a3be8c"
white = "#bf616a"
