# Prism Ocean - Alacritty
[colors.primary]
background = "#0A2133"
foreground = "#348FD5"

[colors.normal]
black = "#0A2133"
red = "#0E566C"
green = "#50B4E2"
yellow = "#34A0A4"
blue = "#0E566C"
magenta = "#34A0A4"
cyan = "#50B4E2"
white = "#348FD5"

[colors.bright]
black = "#0A2133"
red = "#0E566C"
green = "#50B4E2"
yellow = "#34A0A4"
blue = "#0E566C"
magenta = "#34A0A4"
cyan = "#50B4E2"
white = "#348FD5"
