# Prism One Dark Pro - Alacritty
[colors.primary]
background = "#282c34"
foreground = "#c678dd"

[colors.normal]
black = "#282c34"
red = "#e06c75"
green = "#61afef"
yellow = "#98c379"
blue = "#e06c75"
magenta = "#98c379"
cyan = "#61afef"
white = "#c678dd"

[colors.bright]
black = "#282c34"
red = "#e06c75"
green = "#61afef"
yellow = "#98c379"
blue = "#e06c75"
magenta = "#98c379"
cyan = "#61afef"
white = "#c678dd"
