# Prism Rose - Alacritty
[colors.primary]
background = "#140006"
foreground = "#FAE0E4"

[colors.normal]
black = "#140006"
red = "#FF7096"
green = "#F7CAD0"
yellow = "#FF99AC"
blue = "#FF7096"
magenta = "#FF99AC"
cyan = "#F7CAD0"
white = "#FAE0E4"

[colors.bright]
black = "#140006"
red = "#FF7096"
green = "#F7CAD0"
yellow = "#FF99AC"
blue = "#FF7096"
magenta = "#FF99AC"
cyan = "#F7CAD0"
white = "#FAE0E4"
