# Prism Vaporwave - Alacritty
[colors.primary]
background = "#4C1A57"
foreground = "#00E5E8"

[colors.normal]
black = "#4C1A57"
red = "#85FFFB"
green = "#F0F600"
yellow = "#FF3CC7"
blue = "#85FFFB"
magenta = "#FF3CC7"
cyan = "#F0F600"
white = "#00E5E8"

[colors.bright]
black = "#4C1A57"
red = "#85FFFB"
green = "#F0F600"
yellow = "#FF3CC7"
blue = "#85FFFB"
magenta = "#FF3CC7"
cyan = "#F0F600"
white = "#00E5E8"
