# Prism Vesper - Alacritty
[colors.primary]
background = "#F8F8F7"
foreground = "#272727"

[colors.normal]
black = "#272727"
red = "#53132D"
green = "#C39B83"
yellow = "#676266"
blue = "#53132D"
magenta = "#676266"
cyan = "#C39B83"
white = "#F8F8F7"

[colors.bright]
black = "#272727"
red = "#53132D"
green = "#C39B83"
yellow = "#676266"
blue = "#53132D"
magenta = "#676266"
cyan = "#C39B83"
white = "#F8F8F7"
