# Prism Arctic - Alacritty
[colors.primary]
background = "#0A090C"
foreground = "#F0EDEE"

[colors.normal]
black = "#0A090C"
red = "#07393C"
green = "#90DDF0"
yellow = "#2C666E"
blue = "#07393C"
magenta = "#2C666E"
cyan = "#90DDF0"
white = "#F0EDEE"

[colors.bright]
black = "#0A090C"
red = "#07393C"
green = "#90DDF0"
yellow = "#2C666E"
blue = "#07393C"
magenta = "#2C666E"
cyan = "#90DDF0"
white = "#F0EDEE"
