# Prism Catppuccin Mocha - Alacritty
[colors.primary]
background = "#1e1e2e"
foreground = "#fab387"

[colors.normal]
black = "#1e1e2e"
red = "#cba6f7"
green = "#a6e3a1"
yellow = "#f38ba8"
blue = "#cba6f7"
magenta = "#f38ba8"
cyan = "#a6e3a1"
white = "#fab387"

[colors.bright]
black = "#1e1e2e"
red = "#cba6f7"
green = "#a6e3a1"
yellow = "#f38ba8"
blue = "#cba6f7"
magenta = "#f38ba8"
cyan = "#a6e3a1"
white = "#fab387"
