# Prism Synthwave - Alacritty
[colors.primary]
background = "#3A0CA3"
foreground = "#F72585"

[colors.normal]
black = "#3A0CA3"
red = "#560BAD"
green = "#B5179E"
yellow = "#7209B7"
blue = "#560BAD"
magenta = "#7209B7"
cyan = "#B5179E"
white = "#F72585"

[colors.bright]
black = "#3A0CA3"
red = "#560BAD"
green = "#B5179E"
yellow = "#7209B7"
blue = "#560BAD"
magenta = "#7209B7"
cyan = "#B5179E"
white = "#F72585"
