# Prism Tropical - Alacritty
[colors.primary]
background = "#0B6E4F"
foreground = "#D9E76C"

[colors.normal]
black = "#0B6E4F"
red = "#C2095A"
green = "#FF751F"
yellow = "#E42565"
blue = "#C2095A"
magenta = "#E42565"
cyan = "#FF751F"
white = "#D9E76C"

[colors.bright]
black = "#0B6E4F"
red = "#C2095A"
green = "#FF751F"
yellow = "#E42565"
blue = "#C2095A"
magenta = "#E42565"
cyan = "#FF751F"
white = "#D9E76C"
