name = "CoderRules"
version = "0.1.0"
reservoir = false
defaultTargets = ["CoderRules"]

[leanOptions]
pp.unicode.fun = true

[[lean_lib]]
name = "CoderRules"
globs = ["CoderRules", "CoderRules.**"]

[[lean_lib]]
name = "Bridge"
srcDir = "src"
globs = ["Bridge", "Bridge.**"]
